apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  selector:
    app: activemq
  ports:
    - name: amqp
      port: 61616
      targetPort: 61616
    - name: web
      port: 8161
      targetPort: 8161
  type: ClusterIP
