version: "3.8"

networks:
  fromzeroapi:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: webmaster123
    ports:
      - "3307:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pwebmaster123", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fromzeroapi

  eurekaservice:
    build: ../../Eureka-Service
    container_name: eurekaservice
    image: microservice-eureka:v1
    ports:
      - "8761:8761"
    environment:
      EUREKA_SERVER: http://eurekaservice:8761/eureka
    restart: always
    networks:
      - fromzeroapi
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  authservice:
    build: ../../Auth-Service   # carpeta donde está tu Dockerfile
    container_name: authservice
    ports:
      - "9081:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/authdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: webmaster123
      EUREKA_SERVER: http://eurekaservice:8761/eureka
    networks:
      - fromzeroapi

  userservice:
    build: ../../User-Service   # carpeta donde está tu Dockerfile
    container_name: userservice
    ports:
      - "9082:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/usersdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: webmaster123
      EUREKA_SERVER: http://eurekaservice:8761/eureka
    networks:
      - fromzeroapi

  supportservice:
    build: ../../Support-Service   # carpeta donde está tu Dockerfile
    container_name: supportservice
    ports:
      - "9080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/supportticketsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: webmaster123
      EUREKA_SERVER: http://eurekaservice:8761/eureka
    networks:
      - fromzeroapi

  projectsservice:
    build: ../../Project-Service   # carpeta donde está tu Dockerfile
    container_name: projectservice
    ports:
      - "9083:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/projectsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: webmaster123
      EUREKA_SERVER: http://eurekaservice:8761/eureka
    networks:
      - fromzeroapi

  deliverablesservice:
    build: ../../Deliverables-Service   # carpeta donde está tu Dockerfile
    container_name: deliverablesservice
    ports:
      - "9084:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/deliverablesdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: webmaster123
      EUREKA_SERVER: http://eurekaservice:8761/eureka
    networks:
      - fromzeroapi

  notificationsservice:
    build: ../../Notification-Service   # carpeta donde está tu Dockerfile
    container_name: notificationsservice
    ports:
      - "9085:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notificationsdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: webmaster123
      SENDGRID_TEMPLATE_ID: 1
      SENDGRID_API_KEY: 1
      EUREKA_SERVER: http://eurekaservice:8761/eureka
    networks:
      - fromzeroapi

  candidatesservice:
    build: ../../Candidates-Service   # carpeta donde está tu Dockerfile
    container_name: candidatesservice
    ports:
      - "9086:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/candidatesdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: webmaster123
      SENDGRID_TEMPLATE_ID: 1
      SENDGRID_API_KEY: 1
      EUREKA_SERVER: http://eurekaservice:8761/eureka
    networks:
      - fromzeroapi