version: "3.8"

networks:
  fromzeroapi:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: fromzerodb
      MYSQL_ROOT_PASSWORD: Z$varc0SQL
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pZ$varc0SQL", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fromzeroapi

  backend:
    image: supportservice
    container_name: supportservice
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fromzerodb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Z$varc0SQL
    networks:
      - fromzeroapi